### ISSUE TITLE
mac m1 "Library not loaded"

### ISSUE THREAD

**Issue by Yeba** [exaloop/codon#88]
install via bash, run 

```
codon run test.py
```
get error
```
dyld[67860]: Library not loaded: '/opt/homebrew/opt/zstd/lib/libzstd.1.dylib'
  Referenced from: '/Users/xxx/.codon/lib/codon/libcodonc.dylib'
  Reason: tried: '/opt/homebrew/opt/zstd/lib/libzstd.1.dylib' (no such file), '/usr/local/lib/libzstd.1.dylib' (no such file), '/usr/lib/libzstd.1.dylib' (no such file)
zsh: abort test.py
```

**Comment by arshajii** [comment]
Thanks for pointing this out -- the pre-built binary shouldn't be linked to that library. I'll check this for the next release, but in the meantime `brew install zstd` might resolve the issue.

**Comment by arshajii** [comment]
Should be fixed in v0.15.2 release!

**Comment by Yeba** [comment]
`brew install zstd` works! 
By the way, the project is marvelous, I'm waiting for v1.0!

**Comment by inikolaev** [comment]
I've just tried that on my Intel Mac and still getting this error:

```
dyld[53257]: Library not loaded: /usr/local/opt/zstd/lib/libzstd.1.dylib
  Referenced from: <35902E26-B869-3DC7-B6B6-33EC07E5D999> /Users/inikolaev/.codon/lib/codon/libcodonc.dylib
  Reason: tried: '/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '/usr/local/lib/libzstd.1.dylib' (no such file), '/usr/lib/libzstd.1.dylib' (no such file, not in dyld cache)
```

Has this been fixed yet?

**Comment by LowPower-Center** [comment]
I tried this method on my Intel mac, got another error:

zsh: bus error  codon

how can i fix it?
